### ISSUE TITLE
Documentation/examples

### ISSUE THREAD

**Issue by jimmypuckett** [thebrubaker/faker-factory#1]
@tipsy-joel, I was looking at the project today, but are confused by the documentation...

```js
let users = factory('user', 10)->make() // array of fake users
let adminUsers = factory('user', 10)->make({ isAdmin: true }) // array of fake admin users
```

This appears to be a mix of ```js``` & ```php``` code.

I tried this...

```js
let users = factory('user', 10).make()
```

but the signature of the factory is ```constructor (model, callback)```, so I tried...

```js
let users = factory('user').make()
```
 but I still get errors, so I looked at your test code to try this...

```js
factory.getRegisteredFaker('user').callback().email;
```

and I get...

```js 
TypeError: Cannot read property 'name' of undefined
```

This is my factory...

```js
import factory from 'faker-factory';

const User = class User {
    constructor(attributes = {}) {
        this.attributes = attributes;
    }
};

factory.register('user', User, faker => ({
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
}));
```

Am I missing something is is the documentation wrong?

**Comment by jimmypuckett** [comment]
@tipsy-joel,

I was able to get it working...

```js
import factory from 'faker-factory';

const User = class User {
    constructor(attributes = {}) {
        this.attributes = attributes;
    }
};

factory.register('user', User, faker => ({
    firstName: faker.name.firstName(),
    lastName: faker.name.lastName(),
    email: faker.internet.email(),
}));

console.log(factory('user', 10).make());
```

So it does appear to just be a documentation issue in the Readme.

**Comment by thebrubaker** [comment]
aha yes I did have a typo in the documentation! I jump between PHP and javascript as you can see, and used arrow syntax here. Thanks for catching that, pushed an update to the readme.
